services:
  traefik:
    image: docker.io/traefik:3.4.3
    container_name: traefik
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command:
      - --configFile=/etc/traefik/traefik.yml
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
    volumes:
      - ./config/traefik.yml:/etc/traefik/traefik.yml:ro
      - traefik_acme:/etc/traefik/acme
    restart: unless-stopped
    networks:
      - local_network

volumes:
  traefik_acme:
    driver: local
    name: ohm-certificates

networks:
  local_network:
    external: true
    