name: Build images and push to GHCR

on:
  push:
    branches:
      - main
      - staging
      - cgimap
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    outputs:
      branch_tag: ${{ steps.vars.outputs.branch_tag }}
      sha_short: ${{ steps.vars.outputs.sha_short }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set vars
        id: vars
        run: |
          echo "sha_short=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
          
      - name: Login GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          # GITHUB_TOKEN is automatically created by GitHub, you can use it to authenticate in the same repository
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container

      # cgimap
      - name: Build & Push cgimap
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./images/cgimap/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ steps.vars.outputs.repo }}/maramech_cgimap:${{ steps.vars.outputs.sha_short }}
          cache-from: type=registry,ref=ghcr.io/${{ steps.vars.outputs.repo }}/maramech_cgimap:buildcache
          cache-to: type=registry,ref=ghcr.io/${{ steps.vars.outputs.repo }}/maramech_cgimap:buildcache,mode=max

